Repository iijung/minishell, pull requests merged in 2023-05, with the labels that each got.

#28 Feature/execute#6
  src/Makefile
  src/builtin/env.c
  src/execute/executor.c
  src/execute/executor.h
  src/execute/get_heredoc.c
  src/execute/init_pipex.c
  src/execute/run.c
  src/execute/run_pipex.c
  src/minishell.c
Labels: enhancement

#29 Feature/execute#6
  src/execute/executor.c
  src/execute/executor.h
  src/execute/get_heredoc.c
  src/execute/init_pipex.c
  src/execute/run_pipex.c
Labels: feature

#30 Feature/non lr parse#10
  lib/libft/Makefile
  src/Makefile
  src/execute/executor.h
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/minishell.c
  src/parse/parse.c
  src/parse/parse.h
  src/parse/parse_operator.c
  src/parse/parse_util.c
Labels: enhancement

#37 fix: Fix exit_status changing from 256 to 0
  src/execute/run_pipex.c
Labels: bug

#40 Feature/expand#7
  src/Makefile
  src/builtin/env.c
  src/builtin/exit.c
  src/builtin/export.c
  src/environ/env_init.c
  src/environ/environ.c
  src/execute/executor.c
  src/execute/executor.h
  src/execute/init_pipex.c
  src/execute/run_pipex.c
  src/execute/set_pipex.c
  src/lexer/check_lexeme.c
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/parse/syntax.c
  src/parse/syntax_inner_util.h
Labels: bug, enhancement, feature

#46 fix: fix delete_useless_func logic
  src/parse/parse_inner_util.c
Labels: bug

#47 feat: set exit status to 258 when syntax error
  src/minishell.c
Labels: enhancement

#51 fix: '*' expand to non hidden file …
  src/execute/get_wildcard.c
Labels: bug

#54 Feature/redirection all#42
  src/Makefile
  src/builtin/env.c
  src/execute/executor.c
  src/execute/executor.h
  src/execute/init_pipex.c
  src/execute/redirect.c
  src/execute/redirect.h
  src/execute/run_pipex.c
  src/execute/set_pipex.c
  src/expand/combine_string.c
  src/expand/expand.h
  src/expand/get_heredoc.c
  src/expand/get_wildcard.c
Labels: bug, enhancement

#57 fix: cd segfault in macos #41
  src/builtin/cd.c
Labels: bug

#55 Bug/subshell#53
  src/builtin/env.c
  src/execute/executor.c
  src/execute/set_pipex.c
  src/expand/combine_string.c
  src/lexer/get_lexeme.c
  src/lexer/lexer.h
  src/minishell.c
  src/parse/parse.c
  src/parse/parse.h
  src/parse/parse_inner_syntax.c
  src/parse/parse_inner_util.c
  src/parse/parse_inner_util.h
Labels: bug, enhancement

#60 Feature/env redirection#59
  src/expand/combine_string.c
Labels: enhancement

#62 fix: don't check redirect-string pair syntax error
  src/parse/syntax.c
Labels: bug

#64 fix: expand environ + dquote + str + wildcard set
  src/execute/set_pipex.c
  src/expand/combine_string.c
Labels: bug, enhancement

#63 fix: check redirect-filename pair after expand env
  src/execute/redirect.c
  src/execute/set_pipex.c
Labels: bug

#66 Feat/heredoct signal#43
  src/expand/get_heredoc.c
  src/prompt/prompt.c
Labels: enhancement

#71 fix: fix subshell node way
  src/execute/executor.c
Labels: bug

#68 fix: free str in _arg when str[0] == '*'#67
  src/execute/set_pipex.c
Labels: bug

#73 Bug/subshell#70
  src/execute/executor.c
Labels: bug

#75 Refactor/debug#74
  src/execute/set_pipex.c
  src/lexer/get_lexeme.c
  src/lexer/lexer.c
  src/lexer/lexer.h
  src/minishell.c
  src/parse/parse_util.c
  test/README.md
  test/test.mk
Labels: enhancement

#78 fix/exit_status logic#77
  src/environ/environ.h
  src/execute/executor.c
  src/minishell.c
Labels: enhancement

#81 Release v1.0
  src/execute/executor.c
  src/execute/executor.h
  src/execute/init_pipex.c
  src/execute/run_pipex.c
  src/expand/get_heredoc.c
  src/parse/syntax.c
Labels: enhancement

#83 fix: fix recursive logic in is_syntax_error func
  src/parse/syntax.c
Labels: bug

#84 Refactor
  src/builtin/builtin.c
  src/builtin/builtin.h
  src/builtin/cd.c
  src/builtin/echo.c
  src/builtin/env.c
  src/builtin/exit.c
  src/builtin/export.c
  src/builtin/unset.c
  src/execute/executor.c
  src/execute/executor.h
  src/execute/run_pipex.c
  src/minishell.c
  src/prompt/prompt.c
Labels: enhancement

#86 print_error message when no delimiter#85
  src/execute/redirect.c
Labels: enhancement

#88 Enhance/no builtin#87
  src/builtin/builtin.c
  src/builtin/cd.c
  src/execute/executor.c
Labels: bug, enhancement

#89 Release v1.0
  src/builtin/builtin.c
  src/builtin/builtin.h
  src/builtin/cd.c
  src/builtin/echo.c
  src/builtin/env.c
  src/builtin/exit.c
  src/builtin/export.c
  src/builtin/unset.c
  src/execute/executor.c
  src/execute/executor.h
  src/execute/run_pipex.c
  src/minishell.c
  src/prompt/prompt.c
Labels: bug, enhancement

#91 fix: edit operator order
  src/Makefile
  src/environ/environ.c
  src/execute/executor.c
  src/parse/parse.c
  src/parse/parse_inner_getter.c
  src/parse/parse_inner_getter2.c
  src/parse/parse_inner_util.h
Labels: bug

#92 fix: ignore SIGQUIT in heredoc
  src/expand/get_heredoc.c
  src/prompt/prompt.c
  src/prompt/prompt.h
Labels: bug, enhancement
